export interface ResourceConfig {
  name: string;
  label: string;
  path: string;
  fields?: {
    name: string;
    label: string;
    type: string;
  }[];
}

export const adminResources: ResourceConfig[] = [
  // your resources here
];
  {
    table: "members",
    title: "Member Management",
    description: "Manage members, profiles, QR codes and ID cards.",
    path: "members",
    adminOnly: true,
    searchable: [
      "member_id",
      "membership_number",
      "full_name",
      "mobile_number",
      "studio_name",
      "village",
    ],
    fields: [
      { name: "member_id", label: "Member ID", type: "text", readonly: true },
      { name: "membership_number", label: "Membership Number", type: "text" },
      { name: "full_name", label: "Full Name", type: "text", required: true },
      { name: "father_name", label: "Father Name", type: "text" },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { name: "date_of_birth", label: "DOB", type: "date" },
      { name: "blood_group", label: "Blood Group", type: "select", options: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"] },
      { name: "mobile_number", label: "Mobile Number", type: "text", required: true },
      { name: "whatsapp_number", label: "WhatsApp Number", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "aadhaar_number", label: "Aadhaar Number", type: "text" },
      { name: "studio_name", label: "Studio Name", type: "text" },
      { name: "experience", label: "Experience", type: "number" },
      { name: "joining_date", label: "Joining Date", type: "date" },
      { name: "photo_url", label: "Profile Photo URL", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "village", label: "Village", type: "text" },
      { name: "mandal", label: "Mandal", type: "text" },
      { name: "district", label: "District", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "pin_code", label: "PIN Code", type: "text" },
      { name: "emergency_contact", label: "Emergency Contact", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
  },
  {
    table: "kutumbha_bharosa",
    title: "Kutumbha Bharosa",
    description: "Manage registrations, nominee details and reports.",
    path: "kutumbha-bharosa",
    adminOnly: true,
    searchable: ["nominee_name", "nominee_mobile", "status"],
    fields: [
      { name: "member_id", label: "Member UUID", type: "text", required: true },
      { name: "nominee_name", label: "Nominee Name", type: "text", required: true },
      { name: "relation", label: "Relation", type: "text", required: true },
      { name: "nominee_mobile", label: "Nominee Mobile", type: "text" },
      { name: "nominee_aadhaar", label: "Nominee Aadhaar", type: "text" },
      { name: "joining_date", label: "Joining Date", type: "date" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "active", "inactive"] },
    ],
  },
  {
    table: "fund_collections",
    title: "Yearly Fund Collection",
    description: "Manage yearly funds, receipts and dues.",
    path: "funds",
    adminOnly: true,
    searchable: ["receipt_number", "financial_year", "payment_mode", "reference_number"],
    fields: [
      { name: "receipt_number", label: "Receipt Number", type: "text", readonly: true },
      { name: "member_id", label: "Member UUID", type: "text", required: true },
      { name: "financial_year", label: "Financial Year", type: "text", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "payment_date", label: "Payment Date", type: "date" },
      { name: "payment_mode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Bank Transfer", "Cheque"] },
      { name: "reference_number", label: "Reference Number", type: "text" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    table: "loans",
    title: "Loan Management",
    description: "Manage loans, EMI schedules, payments and closing.",
    path: "loans",
    adminOnly: true,
    searchable: ["loan_number", "loan_type", "status", "guarantor"],
    fields: [
      { name: "loan_number", label: "Loan Number", type: "text", readonly: true },
      { name: "member_id", label: "Member UUID", type: "text", required: true },
      { name: "loan_amount", label: "Loan Amount", type: "number", required: true },
      { name: "interest", label: "Interest", type: "number" },
      { name: "interest_type", label: "Interest Type", type: "select", options: ["flat", "reducing"] },
      { name: "loan_type", label: "Loan Type", type: "text", required: true },
      { name: "emi", label: "EMI", type: "number" },
      { name: "installments", label: "Installments", type: "number" },
      { name: "issue_date", label: "Issue Date", type: "date" },
      { name: "due_date", label: "Due Date", type: "date" },
      { name: "balance", label: "Balance", type: "number" },
      { name: "status", label: "Status", type: "select", options: ["active", "closed", "pending"] },
      { name: "guarantor", label: "Guarantor", type: "text" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    table: "loan_payments",
    title: "EMI Payments",
    description: "Collect and track EMI payments.",
    path: "loan-payments",
    adminOnly: true,
    searchable: ["receipt_number", "payment_mode", "reference_number"],
    fields: [
      { name: "loan_id", label: "Loan UUID", type: "text", required: true },
      { name: "receipt_number", label: "Receipt Number", type: "text", readonly: true },
      { name: "payment_date", label: "Payment Date", type: "date" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "penalty", label: "Penalty", type: "number" },
      { name: "payment_mode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Bank Transfer", "Cheque"] },
      { name: "reference_number", label: "Reference Number", type: "text" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    table: "income",
    title: "Income",
    description: "Manage association income.",
    path: "income",
    adminOnly: true,
    searchable: ["category", "payment_mode", "reference"],
    fields: [
      { name: "category", label: "Category", type: "text", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "date", label: "Date", type: "date" },
      { name: "payment_mode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Bank Transfer", "Cheque"] },
      { name: "reference", label: "Reference", type: "text" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    table: "expenses",
    title: "Expenses",
    description: "Manage association expenses.",
    path: "expenses",
    adminOnly: true,
    searchable: ["category", "payment_mode", "reference"],
    fields: [
      { name: "category", label: "Category", type: "text", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "date", label: "Date", type: "date" },
      { name: "payment_mode", label: "Payment Mode", type: "select", options: ["Cash", "UPI", "Bank Transfer", "Cheque"] },
      { name: "reference", label: "Reference", type: "text" },
      { name: "remarks", label: "Remarks", type: "textarea" },
    ],
  },
  {
    table: "events",
    title: "Events",
    description: "Manage meetings, workshops, trainings and competitions.",
    path: "events",
    adminOnly: true,
    searchable: ["title", "event_type", "venue"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "event_type", label: "Event Type", type: "select", options: ["Association Meeting", "Photography Workshop", "Training Program", "Competition"] },
      { name: "description", label: "Description", type: "textarea" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "event_date", label: "Event Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: ["active", "inactive", "archived"] },
    ],
  },
  {
    table: "gallery",
    title: "Photo Gallery",
    description: "Manage albums, photos and videos.",
    path: "gallery",
    adminOnly: true,
    searchable: ["album_name", "title", "media_type"],
    fields: [
      { name: "album_name", label: "Album Name", type: "text", required: true },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "media_type", label: "Media Type", type: "select", options: ["photo", "video"] },
      { name: "media_url", label: "Media URL", type: "text", required: true },
    ],
  },
  {
    table: "notices",
    title: "Notice Board",
    description: "Create notices, upload PDFs and archive notices.",
    path: "notices",
    adminOnly: true,
    searchable: ["title", "content", "status"],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "textarea" },
      { name: "pdf_url", label: "PDF URL", type: "text" },
      { name: "status", label: "Status", type: "select", options: ["active", "archived"] },
      { name: "publish_date", label: "Publish Date", type: "date" },
      { name: "archive_date", label: "Archive Date", type: "date" },
    ],
  },
];
